### ISSUE TITLE
Allow to add labels to Deployment

### ISSUE THREAD

**Issue by bruno-s-coelho** [snyk/snyk-broker-helm#119]
Hello,

While I was using the Helm chart, I noticed that we can add new pod specifications (`extraPodSpecs`).
However, we would also like to add new labels in Deployment. 

As we can see, the Deployment labels are defined [here](https://github.com/snyk/snyk-broker-helm/blob/main/charts/snyk-broker/templates/broker_deployment.yaml#L7) with helpers.

Would be possible to update the helpers to allow to add new labels?
https://github.com/snyk/snyk-broker-helm/blob/main/charts/snyk-broker/templates/_helpers.tpl#L33-L43

Something like the following specs?

**_helpers.tpl**

```
{{/*
Common labels
*/}}
{{- define "snyk-broker.labels" -}}
helm.sh/chart: {{ include "snyk-broker.chart" . }}
{{ include "snyk-broker.selectorLabels" . }}
{{- if .Values.labels }}
{{ toYaml .Values.labels }}
{{- end }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

``` 

**values.yaml**
```
...
labels: {}
....
``` 

Thanks,
Bruno

**Comment by saumilmac** [comment]
Hey Bruno, Thanks for reaching out to us. The support for extra labels has been added in the latest version.
