### ISSUE TITLE
Horizontal pod autoscaler template is not available in snyk broker helm chart version 2.6.8 & 2.6.9

### ISSUE THREAD

**Issue by kamalagg2411** [snyk/snyk-broker-helm#121]
ISSUE: Autoscaling logic is not working and didn't see HPA yaml templates in SNYK broker helm chart 

https://github.com/snyk/snyk-broker-helm/blob/main/charts/snyk-broker/values.yaml#L442
<img width="365" alt="image" src="https://github.com/snyk/snyk-broker-helm/assets/39497271/f97d4302-60c8-4c2c-93f6-ab5484c92e67">

https://github.com/snyk/snyk-broker-helm/blob/main/charts/snyk-broker/templates/broker_deployment.yaml#L9

Helm chart version: 2.6.8

**Comment by soniqua** [comment]
Thanks for the issue. We've reviewed this, and have removed the autoscaling values. Broker is not intended to be autoscaled, and should instead be configured with static replica counts using [High Availability Mode](https://docs.snyk.io/enterprise-configuration/snyk-broker/high-availability-mode).
