### ISSUE TITLE
Possible memory leak in 2.6.7

### ISSUE THREAD

**Issue by thehandsomezebra** [snyk/snyk-broker-helm#136]
Currently we are using 2.6.7 and we began seeing this error

```
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [TLSSocket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
```

Is this a memory leak?

**Comment by aarlaud** [comment]
It's not a memory leak.we have more than 10 event listeners (11 actually) which triggers this warning. No concerns there
