### ISSUE TITLE
Helm chart does not implement health checks

### ISSUE THREAD

**Issue by mschultz-aofl** [snyk/snyk-broker-helm#16]
Currently, the helm chart doesn't implement kubernetes health checks. This means that if the brokers can't connect to SCM/Snyk, they sit there without logging errors and without doing anything. We need this resolved so we can better resolve issues if/when they arise. Ideally, the health check would check both /systemcheck and /healthcheck to ensure that there's a connection to both SCM and Snyk. The pods should be restarted if either of these checks fail (or some third route that checks both).

**Comment by ropnop** [comment]
This is a blocker for us deploying internally as well as we need better monitoring on the health of the broker. I opened a PR to add liveness and readiness probes in the chart: #23

**Comment by aarlaud** [comment]
Closing this as it seemed to have been merged. Please reopen an issue if necessary (clean up mode here a little ;) )
