### ISSUE TITLE
Unable to deploy multiple releases in same namespace

### ISSUE THREAD

**Issue by ropnop** [snyk/snyk-broker-helm#28]
The README mentions that you should be able to deploy multiple releases in an existing namespace, and that this is the preferred way to scale since having more than one pod in the replicaset can cause problems.

However because the Helm chart templates don't use the release name in the resource names, trying to deploy multiple releases of the same chart causes errors with duplicate names for secrets, deployments, etc

I think all resources in the `templates` directory should include the release name in their name to avoid these conflicts

**Comment by soniqua** [comment]
Thanks for raising this issue! We have included this capability in all versions of Snyk Broker Helm since `2.0.0`.
