### ISSUE TITLE
Missing definition for variable acceptJsonFile in helm chart 1.7.0

### ISSUE THREAD

**Issue by ltomasik** [snyk/snyk-broker-helm#68]
We deployed Snyk Broker + Code Agent in AWS EKS with Helm [(1.7.0)](https://github.com/snyk/snyk-broker-helm/tree/snyk-broker-1.7.0) according to the [official documentations](https://docs.snyk.io/enterprise-setup/snyk-broker/snyk-broker-code-agent/install-broker-for-code-agent-using-helm). We found out that variable "**--set acceptJsonFile=accept.json**" used in command helm install isn't defined within helm chart. It means that K8s ConfigMap wasn't created automatically from templates/accept_configmap.yaml. When we adjusted variable to "**--set-file acceptJson=accept.json**", it worked as it should be - K8s ConfigMap with content of "accept.json" file was created and mounted inside container. Alternative option how to place content of file into ConfigMap would be to use helm utility function e.g.(.Files.Glob .Values.acceptJsonFile").AsConfig

**Comment by aarlaud** [comment]
Thanks for the note. We'll take a look

**Comment by aarlaud** [comment]
Hi, updated the docs accordingly. Please note that mounting this file is not really needed and will be decommissioned soon, in favor of a tighter management of these filter rules. 
closing this now. ping me if anything.
