### ISSUE TITLE
I deployed snyk-broker container-registry-agent not working with harbor container registry

### ISSUE THREAD

**Issue by kodani** [snyk/snyk-broker-helm#9]
I've deployed the snyk-broker container-registry agent helm chart on the same envrionment where the harbor is deployed. I've provided harbor credentials to connect and scan images stored in the harbor. Snyk broker is not working. 

`{"name":"snyk-broker","hostname":"container-registry-agent-broker-55b5f6bc44-dmjz4","pid":1,"level":30,"method":"post","path":"/discover","msg":"adding new filter rule","time":"2022-06-11T09:46:23.795Z","v":0}
{"name":"snyk-broker","hostname":"container-registry-agent-broker-55b5f6bc44-dmjz4","pid":1,"level":30,"method":"post","path":"/scan","msg":"adding new filter rule","time":"2022-06-11T09:46:23.795Z","v":0}
{"name":"snyk-broker","hostname":"container-registry-agent-broker-55b5f6bc44-dmjz4","pid":1,"level":30,"port":"8000","msg":"local server is listening","time":"2022-06-11T09:46:23.866Z","v":0}
{"name":"snyk-broker","hostname":"container-registry-agent-broker-55b5f6bc44-dmjz4","pid":1,"level":30,"rulesCount":3,"msg":"loading new rules","time":"2022-06-11T09:46:23.869Z","v":0}
{"name":"snyk-broker","hostname":"container-registry-agent-broker-55b5f6bc44-dmjz4","pid":1,"level":30,"method":"post","path":"/api/v1/import/app","msg":"adding new filter rule","time":"2022-06-11T09:46:23.869Z","v":0}
{"name":"snyk-broker","hostname":"container-registry-agent-broker-55b5f6bc44-dmjz4","pid":1,"level":30,"method":"post","path":"/api/v2/import/done","msg":"adding new filter rule","time":"2022-06-11T09:46:23.869Z","v":0}
{"name":"snyk-broker","hostname":"container-registry-agent-broker-55b5f6bc44-dmjz4","pid":1,"level":30,"method":"post","path":"/api/v2/import/result","msg":"adding new filter rule","time":"2022-06-11T09:46:23.869Z","v":0}
{"name":"snyk-broker","hostname":"container-registry-agent-broker-55b5f6bc44-dmjz4","pid":1,"level":30,"url":"https://broker.snyk.io","token":"${BROKER_TOKEN}","identifyingMetadata":{"version":"4.126.2","filters":{"public":[{"//":"image scan (discover) callback (v1)","method":"POST","path":"/api/v1/import/app"},{"//":"image scan done callback (v2)","method":"POST","path":"/api/v2/import/done"},{"//":"image scan result callback (v2)","method":"POST","path":"/api/v2/import/result"}],"private":[{"method":"GET","path":"/healthcheck","origin":"${CR_AGENT_URL}"},{"//":"validates credentials with connection to container registry","method":"GET","path":"/validate-credentials","origin":"${CR_AGENT_URL}"},{"//":"returns image state id used in recurring or re-tests","method":"GET","path":"/get-state-identifier","origin":"${CR_AGENT_URL}"},{"//":"lists repositories in container registry","method":"GET","path":"/list","origin":"${CR_AGENT_URL}"},{"//":"lists tags/images in a repository","method":"GET","path":"/list/*","origin":"${CR_AGENT_URL}"},{"//":"accepts image scan requests (v1)","method":"POST","path":"/discover","origin":"${CR_AGENT_URL}"},{"//":"accepts image scan requests (v2)","method":"POST","path":"/scan","origin":"${CR_AGENT_URL}"}]}},"msg":"successfully established a websocket connection to the broker server","time":"2022-06-11T09:46:24.611Z","v":0}
Logs from 01/02/2001, 00:00:00`

**Comment by aarlaud** [comment]
Apologies the delay.
Please open a ticket with Snyk support if you still need assistance here.
